name: newsapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  http: ^1.3.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true
  assets :
    - assets/splash_screen.png

flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
